<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>J2534</RootNamespace>
    <AssemblyName>OpenMoose</AssemblyName>
    <ApplicationIcon>mooseicon.ico</ApplicationIcon>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Platforms>AnyCPU</Platforms>
    <Configurations>Debug;Release</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="J2534">
      <HintPath>lib\J2534.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
    <None Include="Resources\moose.jpg" />
    <None Include="Resources\tmp.tmp" />
  </ItemGroup>
</Project>
